apiVersion: v1
kind: Service
metadata:
  name: photoshare-client-svc
  namespace: photoshare
  labels:
    app: photoshare
    component: client
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: photoshare
    component: client
